FROM node:22-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    postgresql-client \
    git \
    # Install Cypress dependencies https://docs.cypress.io/app/get-started/install-cypress#UbuntuDebian
    libgtk2.0-0 \
    libgtk-3-0 \
    libgbm-dev \
    libnotify-dev \
    libnss3 \
    libxss1 \
    libasound2 \
    libxtst6 \
    xauth \
    xvfb

COPY . .
RUN npm install
RUN npx cypress install

EXPOSE 3000

CMD ["npm", "run", "dev"]