name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: database
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm install

      - name: Code Analysis
        run: npm run analyse:check

      - name: Code Formatting
        run: npm run format:check

      - name: Build Project
        run: npm run build

      - name: Start Server
        run: |
          echo "Retrieving environment variables from .env.example excluding database-related variables"
          grep -v "^DB_HOST\|^DB_NAME\|^DB_USER\|^DB_PASSWORD" .env.example > .env
          cat .env
          export $(grep -v '^#' .env | xargs)
          echo "Exporting environment variables related to the database"
          export DB_HOST=localhost DB_NAME=database DB_USER=admin DB_PASSWORD=secret
          node .output/server/index.mjs &
          sleep 3

      - name: Run Cypress Tests
        run: npm run cy:check

      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 5
